#!/bin/bash

NTasks=3
seed_file=seed.txt
Child_No='2'
Shear_rate='0.01'
exe=./lmp

#Total run is 100 starting points per batch each mapped 4 times giving 400 children  
# so with 1000 batches, a total of 4 x 100 x 1000 trajectories, 
for ((TASK_ID=1;TASK_ID<="${NTasks}";TASK_ID++)) 
do

    #Create trajectory structure for current batch of children
    mkdir batch$TASK_ID
    cp mother.in batch$TASK_ID/
    cp child.in batch$TASK_ID/
    cp slab.lmp batch$TASK_ID/
    cp vel.lmp batch$TASK_ID/
    cp force.lmp batch$TASK_ID/
    cp force_equil.lmp batch$TASK_ID/
    cp sim_params.lmp batch$TASK_ID/
    cp ${seed_file} batch$TASK_ID/
    cp ${exe} batch$TASK_ID/

    cd batch$TASK_ID

    seed_v=`sed -n ${TASK_ID}p ${seed_file}`

    #Run equilibration
    mpirun -np 1 ${exe} -screen none -var rseed ${seed_v} -in mother_equil.in

    #Run mother trajectory to create all children starting points
    mpirun -np 1 ${exe} -screen none -var rseed ${seed_v} -var Nchild "${Child_No}" -in mother_gen_branches.in 

    #The total number of restart files generated to spawn children from
    for ((i=1;i<="${Child_No}";i++))
    do
        #Move branch i to current working branch
        mv branch$i.dat branch.dat

        #Each restart is mapped 4 times so we have 4 children (quadruplets) per restart
        for ((j=1;j<=4;j++))
        do
            #Run a child trajectory with 4 mappings (map handled in lammps input)
            mpirun -np 1 ${exe} -screen none -var map "${j}" -var child_index "${i}" -var srate "${Shear_rate}" -in child.in
            #echo "mpi child"
        done
    done
    cd ../
done
